package main

import "GoProject/Calculator"

func main() {

	operations.AddInt8()
	operations.AddInt16()
	operations.AddInt32()
	operations.AddInt64()
	operations.AddUInt8()
	operations.AddUInt16()
	operations.AddUInt32()
	operations.AddUInt64()
	operations.AddFloat32()
	operations.SubInt8()
	operations.SubInt16()
	operations.SubInt32()
	operations.SubInt64()
	operations.SubUInt8()
	operations.SubUInt16()
	operations.SubUInt32()
	operations.SubUInt64()
	operations.DivInt8()
	operations.DivInt16()
	operations.DivInt32()
	operations.DivInt64()
	operations.DivUInt8()
	operations.DivUInt16()
	operations.DivUInt32()
	operations.DivUInt64()
	operations.Divfloat32()
	operations.Divfloat64()
	operations.MulInt8()
	operations.MulInt16()
	operations.MulInt32()
	operations.MulInt64()
	operations.MulUInt8()
	operations.MulUInt16()
	operations.MulUInt32()
	operations.MulUInt64()
	operations.MulFloat32()
	operations.MulFloat64()
}
